[package]
name = "known-types-localai"
version.workspace = true
authors.workspace = true
edition.workspace = true
#rust-version.workspace = true
description = "Well-known types for local.ai data."
#documentation.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["known-types", "localai", "api", "serde"]
categories.workspace = true
publish.workspace = true

[features]
default = ["all", "std"]
all = []
alloc = ["musli?/alloc", "serde?/alloc"]
std = [
    "alloc",
    "borsh?/std",
    "musli?/std",
    "serde?/std",
]
unstable = []

# Interoperability:
async-graphql = ["dep:async-graphql", "std"]
sqlx = ["dep:sqlx", "std"]
sqlx-mysql = ["sqlx", "sqlx/mysql"]
sqlx-postgres = ["sqlx", "sqlx/postgres"]
sqlx-sqlite = ["sqlx", "sqlx/sqlite"]

[dependencies]
known-types = { workspace = true }
derive_more = { workspace = true, features = ["as_ref", "display"] }

# Interoperability:
async-graphql = { workspace = true, optional = true }
borsh = { workspace = true, optional = true }
libsql = { workspace = true, optional = true }
musli = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
sqlx = { workspace = true, optional = true }
